# Generated by Django 3.2 on 2021-04-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Gerne',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('gerne_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.gerne')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
        ),
    ]
